### ISSUE TITLE
CSRF token validation is incomplete (does not validate uniqueness per browser session)

### ISSUE THREAD

**Issue by mkiesel** [aekasitt/fastapi-csrf-protect#11]
I.e., there's no code corresponding to this
https://github.com/IndominusByte/fastapi-jwt-auth/blob/a6c06193319da0e4976c7472966f3a2891e0d50c/fastapi_jwt_auth/auth_jwt.py#L516-L521
or this
https://github.com/wtforms/flask-wtf/blob/72419060c0ce71c002098e304121f7b61c7ec985/src/flask_wtf/csrf.py#L118-L119
which check the CSRF token value supplied in POST form data or request headers against the value the library associates with the user session.

(from https://github.com/aekasitt/fastapi-csrf-protect/issues/10)

**Comment by aekasitt** [comment]
This is not a JWT Auth library so it is definitely going to distinguish uniqueness per user.

---

The separation between `validate_csrf_in_cookies` and `validate_csrf` (used when token is attached in headers) is deliberate as seen on README.md, left at the discretion of developers who integrate this extension. (Cookies recommended for enhanced secrecy)

---

The assumption that any payload can go through when the CSRF Token location is left at the discretion of the developer is incorrect as seen played out in tests.

--- 

Are there any SameSite recommendations?

**Comment by aekasitt** [comment]
Can we use the word visit instead of browser session to clarify that no session data is collected?

**Comment by mkiesel** [comment]
Thing is that depending on the approach the CSRF token (validated on server side) doesn't have to be unique per request, it's fine if it's unique per browser (session) (see [Cookie-to-header token pattern](https://en.wikipedia.org/wiki/Cross-site_request_forgery#Cookie-to-header_token) and the [Double Submit Cookie pattern](https://en.wikipedia.org/wiki/Cross-site_request_forgery#Double_Submit_Cookie)).

Concerning SameSite, it's listed in OWASP as "Defense in Depth" as an _additional_ measure. [source](https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html#samesite-cookie-attribute)

**Comment by aekasitt** [comment]
Tremendously helpful! Will work on it as soon as I can. (next week-ish)

**Comment by aekasitt** [comment]
Drop your LN address here if you want sats for your troubles.
