### ISSUE TITLE
MyPy doesn't like the type signature on load_config

### ISSUE THREAD

**Issue by raph90** [aekasitt/fastapi-csrf-protect#13]
I'm getting the following error when following the example code:
![Screenshot 2022-03-17 at 09 25 16](https://user-images.githubusercontent.com/30865601/158778793-a5497deb-a019-495c-a097-3c77b5185369.png)
I've tried finding ways to type it but no luck.

**Comment by aekasitt** [comment]
Noted, I will get on it.
Do you mind sharing the code snippet that caused the issue? I am inexperienced with MyPy.

**Comment by aekasitt** [comment]
Closing. Not reproducible.
