### ISSUE TITLE
Stream consumed

### ISSUE THREAD

**Issue by mlojewski-me** [aekasitt/fastapi-csrf-protect#19]
When I use token_location = "body" I get errror

  File ".../venv/lib/python3.11/site-packages/fastapi_csrf_protect/core.py", line 185, in validate_csrf
   token = self.get_csrf_from_body(await request.body())
                                    ^^^^^^^^^^^^^^^^^^^^
  File ".../venv/lib/python3.11/site-packages/starlette/requests.py", line 236, in body
    async for chunk in self.stream():
  File ".../venv/lib/python3.11/site-packages/starlette/requests.py", line 218, in stream
    raise RuntimeError("Stream consumed")
RuntimeError: Stream consumed

I think this is because fastapi already consumed stream and read body, because I use fastapi.Form dependency in my route
Maybe it will be better to use request.form() instead of await request.body() in validate_csrf

**Comment by aekasitt** [comment]
Please check this [commit](https://github.com/aekasitt/fastapi-csrf-protect/commit/f3746c09b214ce65f7a8254f6509fafde0b58003) if it satisfies your case just the same.

Saw your PR and responded to it my reasoning.

**Comment by mlojewski-me** [comment]
Works good
