### ISSUE TITLE
Unable to start FastAPI after updating fastapi-csrf-protect to v0.3.5 (related to cookie_samesite config)

### ISSUE THREAD

**Issue by mrchoke** [aekasitt/fastapi-csrf-protect#25]
After updating fastapi-csrf-protect to version v0.3.5, FastAPI is unable to start. However, if I remove cookie_samesite from the config, the application can start successfully.

Here is the error message when trying to start the application with cookie_samesite configured:

```
ValidationError: 1 validation error for LoadConfig
cookie_samesite
  Value error, dictionary update sequence element #0 has length 18; 2 is required [type=value_error, input_value='lax', input_type=str]
    For further information visit https://errors.pydantic.dev/2.9/v/value_error
```

### Steps to Reproduce:

1.	Update fastapi-csrf-protect to version v0.3.5.
2.	Configure cookie_samesite in the CSRF settings.
3.	Attempt to start the FastAPI application.

### Expected Behavior:
FastAPI should start successfully with cookie_samesite configured as usual.

### Actual Behavior:
FastAPI fails to start with the above validation error.

### Temporary Workaround:
Removing the cookie_samesite option from the configuration allows the application to start.

**Comment by gabo71096** [comment]
Same issue here.
I had to rollback to 0.3.4 in order to get it working again.

**Comment by gabo71096** [comment]
I think this issue comes from this [commit](https://github.com/aekasitt/fastapi-csrf-protect/commit/d6d12b29474afa336ce50fc6590cf5275d480c62).

**Comment by aekasitt** [comment]
Noted with thanks, will work on this as soon as possible.

**Comment by aekasitt** [comment]
Please check version `0.3.6` for appropriate fixes. I've also added plenty of tests regarding `cookie_samesite` field under `tests/load_config.py` as well and I hope this does not happen again.
