### ISSUE TITLE
examples: form.html missing from repository

### ISSUE THREAD

**Issue by mkiesel** [aekasitt/fastapi-csrf-protect#9]
The `form.html` template referenced in examples is missing in the repository. @aekasitt 

https://github.com/aekasitt/fastapi-csrf-protect/blob/81bbece1dc214de0b0a7395fc21b53433c196214/examples/context.py#L34

> jinja2.exceptions.TemplateNotFound: form.html

**Comment by aekasitt** [comment]
Misread. I'll attach a template.

**Comment by mkiesel** [comment]
Ok!

BTW jinja2 is missing from the "examples" Poetry section:
https://github.com/aekasitt/fastapi-csrf-protect/blob/81bbece1dc214de0b0a7395fc21b53433c196214/poetry.lock#L261

**Comment by aekasitt** [comment]
Must have dropped it when I shifted to poetry. Nice catch!
The form html page is now attached and I added the missing dependency into examples extra.
